#!/bin/bash

if [ $# -ne 1 ]; then
  TGT="."
else
  TGT="$1"
fi


mkdir -p $TGT
cd $TGT
TGT=`pwd`
sed "s|%%TGT%%|$TGT|" > goload << "EOF"

# This file must be used with "source" *from bash*
# you cannot run it directly

gounload () {
    unset GOPATH

    # reset old environment variables
    if [ -n "$_OLD_GODEP_PATH" ] ; then
        PATH="$_OLD_GODEP_PATH"
        export PATH
        unset _OLD_GODEP_PATH
    fi
    # This should detect bash and zsh, which have a hash command that must
    # be called to get it to forget past commands.  Without forgetting
    # past commands the $PATH changes we made may not be respected
    if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
        hash -r 2>/dev/null
    fi

    if [ -n "$_OLD_GODEP_PS1" ] ; then
        PS1="$_OLD_GODEP_PS1"
        export PS1
        unset _OLD_GODEP_PS1
    fi

    if [ ! "$1" = "nondestructive" ] ; then
    # Self destruct!
        unset -f gounload
    fi
}

# unset irrelevant variables
gounload nondestructive

SCRIPT_DIR="%%TGT%%"
export GOPATH="`cd $SCRIPT_DIR; pwd`"

_OLD_GODEP_PATH="$PATH"
PATH="$GOPATH/bin:$PATH"
export PATH

if [ -z "$GODEP_ENV_DISABLE_PROMPT" ] ; then
    _OLD_GODEP_PS1="$PS1"
    if [ "x" != x ] ; then
        PS1="$PS1"
    else
    if [ "`basename \"$GOPATH\"`" = "__" ] ; then
        # special case for Aspen magic directories
        # see http://www.zetadev.com/software/aspen/
        PS1="[`basename \`dirname \"$GOPATH\"\``] $PS1"
    else
        PS1="(`basename \"$GOPATH\"`)$PS1"
    fi
    fi
    export PS1
fi

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
    hash -r 2>/dev/null
fi

# Initialize if not presently set
if [ ! -f $GOPATH/bin/godep ]; then
   echo "Fetching godep from github...."
   go get github.com/tools/godep
fi

VERSION=`godep version 2> /dev/null`
if [ $? -ne 0 ]; then
   echo "Error running godep!"
fi
echo "Loaded godep: $VERSION"
EOF
. goload
